### PR TITLE
Fix foreground layer for multiple displays

### PR DESCRIPTION
**Pull request by SteveEisner**
This is basically PR#2 from the original SmartMatrix repo.  I've updated it to the latest code and tested it against a 64x32 matrix.  There are a few details inside the commit comments and in a discussion at https://plus.google.com/113338764007406375533/posts/aXaA9oYjteY

Hopefully you can use this to update your PR#17.  Thanks - your code was helpful to get me started!

### CODE REVIEW

**Comment by mrwastl** [comment]
i will test it with my 96x64 matrix as soon as i've some time.  i haven't even tested scrolling and stuff like that until now (because i don't need foreground drawing for my projects).

memory: are you using a teensy 3.1?   there should be more than enough memory for your 64x32. i drive a 96x64 matrix with 24 bit colour depth, double buffering and foreground drawing.
if foreground drawing is disabled (#define DISABLE_FOREGROUND_FUNCTIONS) even 32bit is possible ...

**Comment by SteveEisner** [comment]
Yep, I'm on a Teensy 3.1 -- and there's enough for 64x32 -- but it's strange, because as soon as I bump it up to 96x64 it runs past the 15k memory limit.  I didn't dive too deep into the code, but I'm really surprised that the foreground layer would take much memory (it's just 1 bit per pixel per buffer I believe?)

With your 96x64, I think you might see the text scroll across every 32x32 panel as if they were laid out side by side.  It would take more complicated code to make the text scroll correctly in serpentine/C configurations...

**Comment by mrwastl** [comment]
the foreground-stuff eats quite some memory:
static uint32_t foregroundBitmap[2][MATRIX_WIDTH][MATRIX_WIDTH / 32];
=> 1536 bytes  (for my 96x64 matrix - the matrix is internally seen as one big line of chained panels (6 panels in my case) - a convertion function is doing the mapping of the pixels (eg. 6x1 -> 3x2 panels))
but i must admit that i haven't had a deep look into the foreground drawing code - i've only added a define to disable it :)  so i don't really know what it is doing.

**Comment by mrwastl** [comment]
This pull request has been integrated in the current commits (i did not merge it because i removed one dimension of the foregroundBitmap-array to save memory).

**Pull request closed without merging**
